title: VirtualDesktopDevops
description: VirtualDesktopDevops federates community integration efforts to build an highly available, secure, and production grade Citrix XenDesktop environment.
google_site_verification: R71XDERzPOp9lUudi8X6iKrpcoIgDG_1HzRMz_TMaDY
theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
